version: '3'
services:
  mysqldb:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    volumes:
      - ./src/test/resources:/docker-entrypoint-initdb.d